version: '3.8'
                                  
services:
  app:                                          
    build: ./app                                
    container_name: app-container               
    environment:                                
      - NODE_ENV=production                     
      - APP_PORT=8080                           
      - DB_HOST=db                              
    ports:
      - "8080:8080"                             
    volumes:
      - app-data:/app/data                      
    networks:
      - app-network                             
    depends_on:
      - db                                      
    restart: always                             

  db:                                           
    image: postgres:13-alpine                   
    container_name: db-container                
    environment:
      - POSTGRES_USER=admin                     
      - POSTGRES_PASSWORD=secret                
      - POSTGRES_DB=appdb                       
    volumes:
      - db-data:/var/lib/postgresql/data        
    networks:
      - app-network                             
    restart: always                             
    healthcheck:                                
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 30s                             
      retries: 5                                

  redis:                                        
    image: redis:6-alpine                       
    container_name: redis-container             
    networks:
      - app-network                             
    ports:
      - "6379:6379"                             
    restart: always                             

  nginx:                                        
    image: nginx:alpine                         
    container_name: nginx-container             
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
      - app-data:/app/data                      
    ports:
      - "80:80"                                 
    networks:
      - app-network                             
    depends_on:
      - app                                     
    restart: always                             

  adminer:                                      
    image: adminer                              
    container_name: adminer-container           
    ports:
      - "8081:8080"                             
    networks:
      - app-network                             
    restart: always                             

networks:
  app-network:                                  
    driver: bridge                              

volumes:
  app-data:                                     
    driver: local                               
  db-data:                                      
    driver: local                               